language: node_js
node_js:
  - "8.1"
before_install:
  - if [[ `npm -v` < 5* ]]; then npm i -g npm@5; fi
install:
  - npm install -g bower
  - npm install
sudo: false
cache:
  directories:
  - node_modules
  - test/project/node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


